# Generated by Django 5.2.17 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fuelstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
